# Generated by Django 5.0.7 on 2024-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clients_lawyers_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
