# Generated by Django 5.0.7 on 2024-07-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_clients_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_case', models.CharField(choices=[('Criminal', 'Criminal'), ('Family', 'Family'), ('Corporate', 'Corporate'), ('Civil', 'Civil'), ('Intellectual property', 'Intellectual property'), ('Cyber', 'Cyber'), ('Contract', 'Contract')], max_length=100)),
                ('proofs', models.ImageField(default=False, upload_to='')),
                ('Descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lawyer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lawyer', models.CharField(choices=[('Criminal', 'Criminal'), ('Family', 'Family'), ('Corporate', 'Corporate'), ('Civil', 'Civil'), ('Intellectual property', 'Intellectual property'), ('Cyber', 'Cyber'), ('Contract', 'Contract')], default='', max_length=100)),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lawyers')),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='evid.png', upload_to='evidence_images')),
                ('Active', models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True)),
                ('court_name', models.CharField(max_length=200)),
                ('Date_of_hearing', models.DateField(default=None)),
                ('status', models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('ongoing', 'ongoing')], max_length=20)),
                ('Lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lawyers')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clients')),
                ('Description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.register_case')),
            ],
        ),
    ]
