# Generated by Django 5.0.7 on 2024-08-02 18:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_clients_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_case', models.CharField(choices=[('Criminal', 'Criminal'), ('Family', 'Family'), ('Corporate', 'Corporate'), ('Civil', 'Civil'), ('Intellectual property', 'Intellectual property'), ('Cyber', 'Cyber'), ('Contract', 'Contract')], default='Criminal', max_length=100)),
                ('proofs', models.ImageField(default='evid.png', upload_to='evidence_images/')),
                ('Descriptions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=250)),
                ('image', models.ImageField(default='evid.png', upload_to='evidence_images')),
                ('Active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100)),
                ('court_name', models.CharField(max_length=200)),
                ('Date_of_hearing', models.DateField(default=datetime.datetime(2024, 8, 3, 18, 45, 16, 403182))),
                ('status', models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('ongoing', 'ongoing')], default='ongoing', max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clients')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lawyers')),
            ],
        ),
        migrations.CreateModel(
            name='lawyer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lawyer', models.CharField(choices=[('Criminal', 'Criminal'), ('Family', 'Family'), ('Corporate', 'Corporate'), ('Civil', 'Civil'), ('Intellectual property', 'Intellectual property'), ('Cyber', 'Cyber'), ('Contract', 'Contract')], max_length=100)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lawyers')),
            ],
        ),
    ]
