# Generated by Django 5.0.7 on 2024-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_lawyer_type_type_of_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('ongoing', 'ongoing')], default='ongoing', max_length=20),
        ),
    ]
