# Generated by Django 5.0.7 on 2024-08-02 18:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_case_date_of_hearing'),
        ('users', '0006_alter_clients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Date_of_hearing',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 18, 47, 35, 58409)),
        ),
        migrations.AlterField(
            model_name='case',
            name='client_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.clients'),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.lawyers'),
        ),
    ]
