# Generated by Django 5.0.7 on 2024-08-02 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_case_date_of_hearing_alter_case_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Date_of_hearing',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 18, 55, 21, 74663)),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_name',
            field=models.CharField(choices=[('supreme-court', 'supreme-court'), ('high-court', 'high-court'), ('district-court', 'district-court')], default='district-court', max_length=100),
        ),
    ]
