# Generated by Django 5.0.7 on 2024-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_case_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_case',
            name='Descriptions',
            field=models.TextField(null=True),
        ),
    ]
