# Generated by Django 5.0.7 on 2024-08-02 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_case_date_of_hearing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Date_of_hearing',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 19, 13, 11, 527217)),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_name',
            field=models.CharField(choices=[('district-court', 'district-court'), ('supreme-court', 'supreme-court'), ('high-court', 'high-court')], default='district-court', max_length=100),
        ),
        migrations.AlterField(
            model_name='register_case',
            name='type_of_case',
            field=models.CharField(blank=True, choices=[('Criminal', 'Criminal'), ('Family', 'Family'), ('Corporate', 'Corporate'), ('Civil', 'Civil'), ('Intellectual property', 'Intellectual property'), ('Cyber', 'Cyber'), ('Contract', 'Contract')], default='Criminal', max_length=100),
        ),
    ]
