# Generated by Django 5.0.7 on 2024-07-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_register_case_proofs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Active',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='True'),
        ),
    ]
