# Generated by Django 5.0.7 on 2024-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_case_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
    ]
